# Change these first
owner: GreepTheSheep # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository
user-agent: GreepTheSheep

sites:
  - name: Greep website
    url: https://www.greep.gq
    icon: https://raw.githubusercontent.com/GreepTheSheep/greepthesheep.github.io/master/images/icon.png
  - name: Discord Bot - Trackmania.io#5624
    url: $WEBSITE_TMIOBOT_PATH
    icon: https://cdn.discordapp.com/avatars/810191349214871583/3c1cdc77aeb0dd47cf1ce782c79e4c78.png
    headers:
      - "Authorization: Token $WEBSITE_TMIOBOT_TOKEN"
      - "Content-Type: application/json"
  - name: Node-Trackmania.io Docs
    url: https://tmio.greep.gq
    icon: https://greep.gq/images/tmio.png
  - name: Frames In Order - Tangled
    url: https://tangledframesapi.greep.gq/user
    icon: https://greep.gq/images/frames.png

robotsText: "User-agent: * \n Disallow: /"

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.greep.gq
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/GreepTheSheep/greepthesheep.github.io/master/images/icon.png
  name: Greep
  introTitle: 
  introMessage: 
  theme: night
  navbar:
    - title: Website
      href: https://www.greep.gq
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

workflowSchedule:
  graphs: "0 */1 * * *"
  responseTime: "*/15 * * * *"
  staticSite: "0 */3 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 */1 * * *"
  uptime: "*/5 * * * *"

skipDescriptionUpdate: true
skipTopicsUpdate: true

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
